apiVersion: apps/v1
kind: Deployment
metadata:
 name: kplabs-update
spec:
 replicas: 2
 selector:
  matchLabels:
   app: nginxd
 template:
  metadata:
   labels: 
    app: nginxd
  spec:
   containers:
   - name: nginx
     image: quay.io/gauravkumar9130/production:v1
---
apiVersion: v1
kind: Service
metadata:
 name: kplabs-service
spec:
 type: NodePort
 ports:
 - targetPort: 80
   port: 80
   nodePort: 30008
 selector:
  app: nginxd
