apiVersion: v1
kind: Pod
metadata: 
 name: nginx
spec:
 containers:
 - name: nginx-read
   image: quay.io/gauravkumar9130/ubuntu-git 
   tty: true
   readinessProbe:
    exec:
     command:
     - cat
     - /tmp/demo
    initialDelaySeconds: 5
    periodSeconds: 5  