apiVersion: v1
kind: ReplicationController
metadata:
 name: hellorc
spec:
  replicas: 6
  template:
   metadata:
    labels:
     app: fujitsu
   spec:
    containers:
    - name: c1
      image: quay.io/gauravkumar9130/production  


 