apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-web
spec:
 replicas: 5
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: c1
     image: quay.io/gauravkumar9130/mywebapp